Remove the packaged version of libtool for php
The packaged version of libtool is too old, let's remove it so that we
ensure to use the system installed one

```
libtool: Version mismatch error.  This is libtool 2.4.7 Debian-2.4.7-7build1, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.7 Debian-2.4.7-7build1
libtool: and run autoconf again.
make: *** [ext/date/php_date.lo] Error 63
error: Bad exit status from /var/tmp/rpm-tmp.AJZhzC (%build)
```

Ticket: ENT-12312
Changelog: None
Signed-off-by: Lars Erik Wik <lars.erik.wik@northern.tech>